apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-engine-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: dhsstorageaccount
