apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-jobs-pvc
  namespace: data-harmony
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile
  resources:
      requests:
        storage: 1Gi