apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-jobs-pvc
  namespace: data-harmony
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: dhsstorageaccount
  resources:
      requests:
        storage: 1Gi