apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: data-harmony
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
      requests:
        storage: 2Gi