apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: dhsstorageaccount  