apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:2.7.1-python3.11
          command: ["bash", "-c"]
          args:
            - airflow db migrate && airflow users create --username admin --firstname Anblicks --lastname Anblicks --role Admin --email marketing@anblicks.com --password admin && airflow scheduler
          env:
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "False"
            - name: AIRFLOW__CORE__EXECUTOR
              value: "LocalExecutor"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
            - name: AIRFLOW__WEBSERVER_BASE_URL
              value: "http://localhost:8080"
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              value: "46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho="
            - name: JAVA_HOME
              value: "/usr/lib/jvm/java-11-openjdk"
            - name: PATH
              value: "/usr/lib/jvm/java-11-openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          volumeMounts:
            - name: airflow-jobs
              mountPath: /opt/airflow/jobs
            - name: airflow-logs
              mountPath: /opt/airflow/logs
            - name: airflow-dags
              mountPath: /opt/airflow/dags
            - name: airflow-data
              mountPath: /opt/airflow/data
      volumes:
        - name: airflow-jobs
          persistentVolumeClaim:
            claimName: airflow-jobs-pvc
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: airflow-data
          persistentVolumeClaim:
            claimName: airflow-data-pvc