apiVersion: app/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: data-harmony
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: docker.io/bitnami/spark:3.4.1
          command: ["/opt/bitnami/spark/bin/spark-class"]
          args: ["org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
          ports:
            - containerPort: 7077
          env:
            - name: SPARK_WORKER_MEMORY
              value: 4g
            - name: SPARK_MODE
              value: worker
            - name: SPARK_WORKER_CORES
              value: "4"
            - name: SPARK_MASTER_URL
              value: spark://spark-master:7077
            - name: SPARK_HOME
              value: /opt/bitnami/spark
          volumeMounts:
            - name: spark-jobs
              mountPath: /opt/bitnami/spark/jobs
            - name: spark-engine
              mountPath: /opt/bitnami/spark/jobs/python/dataflow-genie
            - name: spark-data
              mountPath: /opt/bitnami/data

      volumes:
        - name: spark-jobs
          persistentVolumeClaim:
            claimName: spark-jobs-pvc
        - name: spark-engine
          persistentVolumeClaim:
            claimName: spark-engine-pvc
        - name: spark-data
          persistentVolumeClaim:
            claimName: spark-data-pvc