apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow
    component: webserver
spec:
  selector:
    app: airflow
    component: webserver
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  type: LoadBalancer
