apiVersion: v1
kind: Service
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
    component: scheduler
spec:
  selector:
    app: airflow
    component: scheduler
  ports:
    - name: scheduler
      port: 8793
      targetPort: 8793