apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  labels:
    app: spark
    component: worker
spec:
  selector:
    app: spark
    component: worker
  ports:
    - name: worker-ui
      port: 8081
      targetPort: 8081
  type: ClusterIP
